---
abstract: 'Cucumber Testing Framework'
author:
  - 'Michael Vu <email@michael.vu>'
build_requires:
  Digest: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Cucumber-Tiny
requires:
  Mo: 0
  Test::Most: 0
version: 0.3
